version: '3.7'
services:
    web_server:
        build: .
        ports:
            - "5001:5001"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis_server
            - MONGO_HOST=mongo_server
            - FLASK_ENV=production
            - FLASK_RUN_PORT=5001
        depends_on:
            - mongo_server
            - redis_server
    redis_server:
        image: redis:6.0.8-alpine
    mongo_server:
      image: bitnami/mongodb:4.2